-- MySQL Script generated by MySQL Workbench
-- 06/08/16 21:43:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_Softreymar
-- -----------------------------------------------------
-- Base de datos del sistema Softreymar.

-- -----------------------------------------------------
-- Schema bd_Softreymar
--
-- Base de datos del sistema Softreymar.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_Softreymar` DEFAULT CHARACTER SET utf8 ;
USE `bd_Softreymar` ;

-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_personas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla',
  `cedula` VARCHAR(15) NULL COMMENT 'numero de identificacion de la persona',
  `nombre` VARCHAR(30) NULL COMMENT 'nombre de la persona ',
  `apellido1` VARCHAR(30) NULL COMMENT 'primer apellidio de la persona ',
  `apellido2` VARCHAR(35) NULL COMMENT 'segundo apellido de la persona ',
  `direccion` VARCHAR(50) NULL COMMENT 'direccion fisica de la persona',
  `telefono` VARCHAR(10) NULL COMMENT 'numero de telefono al que se pueda contactar a la persona',
  `e-mail` VARCHAR(35) NULL COMMENT 'correo para la persona para su posible contacto',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_cliente` (
  `id` INT NOT NULL COMMENT 'identificador de la tabla',
  `tbl_personas_id` INT NOT NULL COMMENT 'identificador de la tabla persona',
  `frecuente` VARCHAR(1) NULL COMMENT 'Si el cliente es frecuente.',
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_cliente_tbl_personas1_idx` (`tbl_personas_id` ASC),
  CONSTRAINT `fk_tbl_cliente_tbl_personas1`
    FOREIGN KEY (`tbl_personas_id`)
    REFERENCES `bd_Softreymar`.`tbl_personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_proyectos_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_proyectos_produccion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador de la tabla asignada para la producción de la empresa.',
  `codigoProyecto` VARCHAR(15) NOT NULL COMMENT 'código único para cada proyecto. Representa un proyecto específico.',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Este campo es asignado para el nombre o descripción del proyectos.',
  `fechaIngreso` DATETIME NOT NULL,
  `fechaEntrega` DATETIME NULL,
  `tbl_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigoProyecto_UNIQUE` (`codigoProyecto` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_tbl_proyectos_produccion_tbl_cliente1_idx` (`tbl_cliente_id` ASC),
  CONSTRAINT `fk_tbl_proyectos_produccion_tbl_cliente1`
    FOREIGN KEY (`tbl_cliente_id`)
    REFERENCES `bd_Softreymar`.`tbl_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_ocupacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_ocupacion` (
  `id` INT NOT NULL COMMENT 'identificador de la tabla',
  `ocupacion` VARCHAR(45) NOT NULL COMMENT 'descripcion sobre la ocupacion del emplado en la empresa',
  `pago` DOUBLE NOT NULL COMMENT 'monto de pago',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_emplados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_emplados` (
  `id` INT NOT NULL,
  `tbl_personas_id` INT NOT NULL,
  `tbl_fechaContrato` VARCHAR(45) NULL COMMENT 'Fecha en la que el empleado inica a laboral con la empresa',
  `tbl_ocupacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_emplados_tbl_personas_idx` (`tbl_personas_id` ASC),
  INDEX `fk_tbl_emplados_tbl_ocupacion1_idx` (`tbl_ocupacion_id` ASC),
  CONSTRAINT `fk_tbl_emplados_tbl_personas`
    FOREIGN KEY (`tbl_personas_id`)
    REFERENCES `bd_Softreymar`.`tbl_personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_emplados_tbl_ocupacion1`
    FOREIGN KEY (`tbl_ocupacion_id`)
    REFERENCES `bd_Softreymar`.`tbl_ocupacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_inventario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `codigo_activo` VARCHAR(20) NULL COMMENT 'identificador del activo',
  `nombre` VARCHAR(30) NULL COMMENT 'Nombre o descripcion del activo',
  `cantidad` VARCHAR(45) NULL COMMENT 'Indica la cantidad de activos del mismo tipo.',
  `fechaIngreso` VARCHAR(30) NULL COMMENT 'Fecha en la que se registro el activo',
  `precio` DOUBLE NULL COMMENT 'Precio del activo',
  `unidadMedida` VARCHAR(5) NULL COMMENT 'Indica la unidad en la que se mide el actvo.',
  `estado` VARCHAR(1) NULL COMMENT 'representa el estado del activo',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_taller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_taller` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tbl_inventario_id` INT NOT NULL,
  `tbl_proyectos_produccion_id` INT NOT NULL,
  `tbl_emplados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_taller_tbl_inventario1_idx` (`tbl_inventario_id` ASC),
  INDEX `fk_tbl_taller_tbl_proyectos_produccion1_idx` (`tbl_proyectos_produccion_id` ASC),
  INDEX `fk_tbl_taller_tbl_emplados1_idx` (`tbl_emplados_id` ASC),
  CONSTRAINT `fk_tbl_taller_tbl_inventario1`
    FOREIGN KEY (`tbl_inventario_id`)
    REFERENCES `bd_Softreymar`.`tbl_inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_taller_tbl_proyectos_produccion1`
    FOREIGN KEY (`tbl_proyectos_produccion_id`)
    REFERENCES `bd_Softreymar`.`tbl_proyectos_produccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_taller_tbl_emplados1`
    FOREIGN KEY (`tbl_emplados_id`)
    REFERENCES `bd_Softreymar`.`tbl_emplados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_pago` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `fecha` VARCHAR(45) NOT NULL COMMENT 'fecha del pago',
  `descripcion` VARCHAR(45) NOT NULL COMMENT 'motivo del pago',
  `tbl_ocupacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_pago_tbl_ocupacion1_idx` (`tbl_ocupacion_id` ASC),
  CONSTRAINT `fk_tbl_pago_tbl_ocupacion1`
    FOREIGN KEY (`tbl_ocupacion_id`)
    REFERENCES `bd_Softreymar`.`tbl_ocupacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_activosUtilizadosProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_activosUtilizadosProyecto` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `tbl_inventario_id` INT NOT NULL COMMENT 'identificador del inventario',
  `tbl_proyectos_produccion_id` INT NOT NULL COMMENT 'identificador del proyecto de produccion',
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_inventario_has_tbl_proyectos_produccion_tbl_proyecto_idx` (`tbl_proyectos_produccion_id` ASC),
  INDEX `fk_tbl_inventario_has_tbl_proyectos_produccion_tbl_inventar_idx` (`tbl_inventario_id` ASC),
  CONSTRAINT `fk_tbl_inventario_has_tbl_proyectos_produccion_tbl_inventario1`
    FOREIGN KEY (`tbl_inventario_id`)
    REFERENCES `bd_Softreymar`.`tbl_inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_inventario_has_tbl_proyectos_produccion_tbl_proyectos_1`
    FOREIGN KEY (`tbl_proyectos_produccion_id`)
    REFERENCES `bd_Softreymar`.`tbl_proyectos_produccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_empleadosAsignadosProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_empleadosAsignadosProyecto` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador de la tabla',
  `tbl_proyectos_produccion_id` INT NOT NULL COMMENT 'identificador del proyecto en produccion',
  `tbl_emplados_id` INT NOT NULL COMMENT 'identificador del empleado en proyecto',
  INDEX `fk_tbl_proyectos_produccion_has_tbl_emplados_tbl_emplados1_idx` (`tbl_emplados_id` ASC),
  INDEX `fk_tbl_proyectos_produccion_has_tbl_emplados_tbl_proyectos__idx` (`tbl_proyectos_produccion_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tbl_proyectos_produccion_has_tbl_emplados_tbl_proyectos_pr1`
    FOREIGN KEY (`tbl_proyectos_produccion_id`)
    REFERENCES `bd_Softreymar`.`tbl_proyectos_produccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_proyectos_produccion_has_tbl_emplados_tbl_emplados1`
    FOREIGN KEY (`tbl_emplados_id`)
    REFERENCES `bd_Softreymar`.`tbl_emplados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_usuarios` (
  `usuario` VARCHAR(20) NOT NULL COMMENT 'usuario unico para acceso al sistema',
  `clave` VARCHAR(45) NOT NULL COMMENT 'Contraseña del usuario',
  `tbl_personas_id` INT NOT NULL COMMENT 'Codigo del registro de los datos personales del usuario',
  PRIMARY KEY (`usuario`),
  INDEX `fk_tbl_usuarios_tbl_personas1_idx` (`tbl_personas_id` ASC),
  CONSTRAINT `fk_tbl_usuarios_tbl_personas1`
    FOREIGN KEY (`tbl_personas_id`)
    REFERENCES `bd_Softreymar`.`tbl_personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_proyecto_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_proyecto_pago` (
  `codigo` VARCHAR(45) NOT NULL COMMENT 'identificador unico del pago.',
  `fecha` DATE NOT NULL COMMENT 'Fecha del pago',
  `tbl_proyectos_produccion_id` INT NOT NULL COMMENT 'Codigo del proyecto pagado',
  `monto` DOUBLE NOT NULL COMMENT 'Cobro sin cargos ni descuentos',
  `descuento` DOUBLE NOT NULL COMMENT 'Descuento por monto',
  `impuesto` DOUBLE NOT NULL COMMENT 'Impuesto por pago',
  `subtotal` DOUBLE NOT NULL COMMENT 'Pago con impuestos',
  `total` DOUBLE NOT NULL COMMENT 'Monto que se le cobro al cliente.',
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codidoSolicitud_UNIQUE` (`codigo` ASC),
  INDEX `fk_tbl_solicitud_tbl_proyectos_produccion1_idx` (`tbl_proyectos_produccion_id` ASC),
  CONSTRAINT `fk_tbl_solicitud_tbl_proyectos_produccion1`
    FOREIGN KEY (`tbl_proyectos_produccion_id`)
    REFERENCES `bd_Softreymar`.`tbl_proyectos_produccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_Softreymar`.`tbl_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_Softreymar`.`tbl_factura` (
  `codigo` VARCHAR(45) NOT NULL COMMENT 'Codigo unico para identificar la factura.',
  `fecha` DATE NOT NULL COMMENT 'Fecha de facturacion.',
  `tbl_taller_id` INT NOT NULL COMMENT 'Identificador de los datos del taller',
  `tbl_usuarios_usuario` VARCHAR(20) NOT NULL COMMENT 'Identificar del usuario que genero la factura.',
  `tbl_proyecto_pago_codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_tbl_factura_tbl_taller1_idx` (`tbl_taller_id` ASC),
  INDEX `fk_tbl_factura_tbl_usuarios1_idx` (`tbl_usuarios_usuario` ASC),
  INDEX `fk_tbl_factura_tbl_proyecto_pago1_idx` (`tbl_proyecto_pago_codigo` ASC),
  CONSTRAINT `fk_tbl_factura_tbl_taller1`
    FOREIGN KEY (`tbl_taller_id`)
    REFERENCES `bd_Softreymar`.`tbl_taller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_tbl_usuarios1`
    FOREIGN KEY (`tbl_usuarios_usuario`)
    REFERENCES `bd_Softreymar`.`tbl_usuarios` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_tbl_proyecto_pago1`
    FOREIGN KEY (`tbl_proyecto_pago_codigo`)
    REFERENCES `bd_Softreymar`.`tbl_proyecto_pago` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
